### ISSUE TITLE
Support for `oidc` provider

### ISSUE THREAD

**Issue by bm1216** [AvitalTamir/cyphernetes#82]
Looks like the shell doesn't support the `oidc` auth provider which can be defined in `~/.kube/config`. 

### Error message
```
Error creating clientset
Error creating QueryExecutor instance: no Auth Provider found for name "oidc"
Cyphernetes Interactive Shell
Type 'exit' or press Ctrl-D to exit
Type 'help' for information on how to use the shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xefa8f21]

goroutine 1 [running]:
main.runShell(0xc0000b5d00?, {0xefad708?, 0x4?, 0xefad70c?})
        /Users/mishrab/Work/cyphernetes/cmd/cyphernetes/shell.go:215 +0x381
github.com/spf13/cobra.(*Command).execute(0x10274480, {0x102ac500, 0x0, 0x0})
        /Users/mishrab/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x10273ec0)
        /Users/mishrab/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/mishrab/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
main.Execute()
        /Users/mishrab/Work/cyphernetes/cmd/cyphernetes/root.go:23 +0x1a
main.main()
        /Users/mishrab/Work/cyphernetes/cmd/cyphernetes/main.go:7 +0xf
```

### Possible solution
If using `client-go`, I think you just have to do 
`import _ "k8s.io/client-go/plugin/pkg/client/auth/oidc"`
in `pkg/parser/k8s_client.go`

**Comment by AvitalTamir** [comment]
Resolved in the v0.11.1 release
